// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "WaniKaniApp",
    platforms: [
        .iOS("15.0")
    ],
    products: [
        .iOSApplication(
            name: "WaniKaniApp",
            targets: ["AppModule"],
            bundleIdentifier: "com.sky.WaniKani",
            teamIdentifier: "52W2H99QHH",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/aaronsky/wanikani-swift", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "WaniKani", package: "wanikani-swift")
            ]
        )
    ]
)