name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - run: mkdir -p DerivedData
      - name: xcodebuild
        working-directory: wanikani-app.swiftpm
        run: |
          xcodebuild \
            -scheme WaniKaniApp \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 13 Pro' \
            -derivedDataPath $(DERIVED_DATA_PATH) \
            -quiet \
            build
  lint:
    runs-on: macOS-11
    env:
      SWIFT_FORMAT_VERSION: '0.50500.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/cache@v2
        with:
          key: swift-format-build-${{ env.SWIFT_FORMAT_VERSION }}
          path: ./swift-format/.build/release/swift-format
      - name: install swift-format
        run: |-
          git clone https://github.com/apple/swift-format.git
          pushd swift-format
          git checkout "tags/${{ env.SWIFT_FORMAT_VERSION }}"
          swift build -c release
          install .build/release/swift-format ~/bin
          popd
      - name: lint
        run: env PATH="$HOME/bin:$PATH" make lint
